workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    # Codemagic UI'da tanımlı App Store Connect integration adı
    integrations:
      app_store_connect: "Lunaura App Store Connect"

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      groups:
        - appstore

      vars:
        API_HOST: "https://fall-production.up.railway.app"
        BUNDLE_ID: "com.anlgzl.lunaura"
        # APP_STORE_APPLE_ID: "1555555551" # (opsiyonel)

      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.anlgzl.lunaura"

    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd mobile/ios
          pod install
          cd ../..

      - name: Set up code signing settings on Xcode project
        script: |
          cd mobile
          xcode-project use-profiles

      # (Opsiyonel ama faydalı) API_HOST gerçekten geliyor mu diye log basar
      - name: Debug env vars
        script: |
          echo "API_HOST=$API_HOST"
          echo "BUNDLE_ID=$BUNDLE_ID"

      - name: Build IPA (release)
        script: |
          cd mobile
          flutter build ipa --release \
            --dart-define=API_HOST=$API_HOST \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - mobile/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
