import 'tarot_models.dart';

class TarotDeck {
  static const List<TarotCard> all = [
    // =========================
    // MAJOR ARCANA (22)
    // =========================
    TarotCard(
      id: 'major_00_fool',
      nameTr: 'Deli',
      nameEn: 'The Fool',
      arcana: 'major',
      suit: '',
      rank: '0',
      keywordsTr: ['başlangıç', 'özgürlük', 'risk'],
      shortMeaningTr: 'Yeni bir yol, taze enerji; plansız ama cesur başlangıç.',
    ),
    TarotCard(
      id: 'major_01_magician',
      nameTr: 'Büyücü',
      nameEn: 'The Magician',
      arcana: 'major',
      suit: '',
      rank: '1',
      keywordsTr: ['niyet', 'güç', 'aksiyon'],
      shortMeaningTr: 'Güç sende; doğru niyet + hamle ile sonuç alırsın.',
    ),
    TarotCard(
      id: 'major_02_high_priestess',
      nameTr: 'Başrahibe',
      nameEn: 'The High Priestess',
      arcana: 'major',
      suit: '',
      rank: '2',
      keywordsTr: ['sezgi', 'sır', 'iç ses'],
      shortMeaningTr: 'Cevap dışarıda değil; iç ses ve işaretler yol gösterir.',
    ),
    TarotCard(
      id: 'major_03_empress',
      nameTr: 'İmparatoriçe',
      nameEn: 'The Empress',
      arcana: 'major',
      suit: '',
      rank: '3',
      keywordsTr: ['bereket', 'şefkat', 'üretim'],
      shortMeaningTr: 'Büyüme ve bereket; sevgiyle kurulan düzen güçlenir.',
    ),
    TarotCard(
      id: 'major_04_emperor',
      nameTr: 'İmparator',
      nameEn: 'The Emperor',
      arcana: 'major',
      suit: '',
      rank: '4',
      keywordsTr: ['düzen', 'otorite', 'sınır'],
      shortMeaningTr: 'Netlik, plan, disiplin; sınır koyarsan güçlenirsin.',
    ),
    TarotCard(
      id: 'major_05_hierophant',
      nameTr: 'Aziz',
      nameEn: 'The Hierophant',
      arcana: 'major',
      suit: '',
      rank: '5',
      keywordsTr: ['gelenek', 'öğreti', 'rehber'],
      shortMeaningTr: 'Değerlerine uygun seçim; doğru kaynak/mentor desteği.',
    ),
    TarotCard(
      id: 'major_06_lovers',
      nameTr: 'Aşıklar',
      nameEn: 'The Lovers',
      arcana: 'major',
      suit: '',
      rank: '6',
      keywordsTr: ['seçim', 'uyum', 'değer'],
      shortMeaningTr: 'Kalp ve akıl arasında seçim; uyum, değerlerle gelir.',
    ),
    TarotCard(
      id: 'major_07_chariot',
      nameTr: 'Savaş Arabası',
      nameEn: 'The Chariot',
      arcana: 'major',
      suit: '',
      rank: '7',
      keywordsTr: ['irade', 'hız', 'kontrol'],
      shortMeaningTr: 'Hedef netse ilerlersin; kontrol sende olmalı.',
    ),
    TarotCard(
      id: 'major_08_strength',
      nameTr: 'Güç',
      nameEn: 'Strength',
      arcana: 'major',
      suit: '',
      rank: '8',
      keywordsTr: ['cesaret', 'sabır', 'öz kontrol'],
      shortMeaningTr: 'Gerçek güç sakinliktir; sabırla yönet.',
    ),
    TarotCard(
      id: 'major_09_hermit',
      nameTr: 'Ermiş',
      nameEn: 'The Hermit',
      arcana: 'major',
      suit: '',
      rank: '9',
      keywordsTr: ['içe dönüş', 'yalnızlık', 'bilgelik'],
      shortMeaningTr: 'Kısa bir çekilme; netleşmek için içe dön.',
    ),
    TarotCard(
      id: 'major_10_wheel',
      nameTr: 'Kader Çarkı',
      nameEn: 'Wheel of Fortune',
      arcana: 'major',
      suit: '',
      rank: '10',
      keywordsTr: ['döngü', 'şans', 'değişim'],
      shortMeaningTr: 'Döngü değişiyor; fırsat kapısı açılabilir.',
    ),
    TarotCard(
      id: 'major_11_justice',
      nameTr: 'Adalet',
      nameEn: 'Justice',
      arcana: 'major',
      suit: '',
      rank: '11',
      keywordsTr: ['denge', 'hak', 'sonuç'],
      shortMeaningTr: 'Ektiğini biçersin; adil karar uzun vadede kazandırır.',
    ),
    TarotCard(
      id: 'major_12_hanged',
      nameTr: 'Asılan Adam',
      nameEn: 'The Hanged Man',
      arcana: 'major',
      suit: '',
      rank: '12',
      keywordsTr: ['bekleme', 'fedakârlık', 'bakış açısı'],
      shortMeaningTr: 'Dur ve farklı açıdan bak; acele zarar verebilir.',
    ),
    TarotCard(
      id: 'major_13_death',
      nameTr: 'Ölüm',
      nameEn: 'Death',
      arcana: 'major',
      suit: '',
      rank: '13',
      keywordsTr: ['bitiriş', 'dönüşüm', 'yenilenme'],
      shortMeaningTr: 'Bir şey kapanıyor; yeni sayfa için alan açılıyor.',
    ),
    TarotCard(
      id: 'major_14_temperance',
      nameTr: 'Denge',
      nameEn: 'Temperance',
      arcana: 'major',
      suit: '',
      rank: '14',
      keywordsTr: ['uyum', 'iyileşme', 'ölçü'],
      shortMeaningTr: 'Aşırılardan uzak; adım adım uyum.',
    ),
    TarotCard(
      id: 'major_15_devil',
      nameTr: 'Şeytan',
      nameEn: 'The Devil',
      arcana: 'major',
      suit: '',
      rank: '15',
      keywordsTr: ['bağımlılık', 'takıntı', 'tuzak'],
      shortMeaningTr: 'Bağlayan bir şey var; sınır koyup özgürleş.',
    ),
    TarotCard(
      id: 'major_16_tower',
      nameTr: 'Kule',
      nameEn: 'The Tower',
      arcana: 'major',
      suit: '',
      rank: '16',
      keywordsTr: ['sarsıntı', 'gerçek', 'yıkım'],
      shortMeaningTr: 'Ani fark ediş; eski yapı yıkılıp gerçek ortaya çıkar.',
    ),
    TarotCard(
      id: 'major_17_star',
      nameTr: 'Yıldız',
      nameEn: 'The Star',
      arcana: 'major',
      suit: '',
      rank: '17',
      keywordsTr: ['umut', 'şifa', 'ilham'],
      shortMeaningTr: 'Umut geri geliyor; toparlanma başlar.',
    ),
    TarotCard(
      id: 'major_18_moon',
      nameTr: 'Ay',
      nameEn: 'The Moon',
      arcana: 'major',
      suit: '',
      rank: '18',
      keywordsTr: ['belirsizlik', 'korku', 'sezgi'],
      shortMeaningTr: 'Net olmayan durum; sezgini dinle, acele hüküm verme.',
    ),
    TarotCard(
      id: 'major_19_sun',
      nameTr: 'Güneş',
      nameEn: 'The Sun',
      arcana: 'major',
      suit: '',
      rank: '19',
      keywordsTr: ['başarı', 'neşe', 'açıklık'],
      shortMeaningTr: 'Açık sonuç; enerji yükselir, işler netleşir.',
    ),
    TarotCard(
      id: 'major_20_judgement',
      nameTr: 'Mahkeme',
      nameEn: 'Judgement',
      arcana: 'major',
      suit: '',
      rank: '20',
      keywordsTr: ['uyanış', 'karar', 'yeniden doğuş'],
      shortMeaningTr: 'Karar zamanı; geçmiş kapanır, yeni sayfa açılır.',
    ),
    TarotCard(
      id: 'major_21_world',
      nameTr: 'Dünya',
      nameEn: 'The World',
      arcana: 'major',
      suit: '',
      rank: '21',
      keywordsTr: ['tamamlanma', 'başarı', 'kapanış'],
      shortMeaningTr: 'Döngü tamam; sonuç alınır, yeni döngü başlar.',
    ),

    // =========================
    // MINOR ARCANA (56)
    // WANDS (Değnekler) 14
    // =========================
    TarotCard(
      id: 'wands_ace',
      nameTr: 'Değnek Ası',
      nameEn: 'Ace of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: 'ace',
      keywordsTr: ['ilham', 'başlangıç', 'cesaret'],
      shortMeaningTr: 'Yeni fikir/ateş; başlatacak kıvılcım.',
    ),
    TarotCard(
      id: 'wands_2',
      nameTr: 'Değnek İkilisi',
      nameEn: 'Two of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: '2',
      keywordsTr: ['plan', 'vizyon', 'seçim'],
      shortMeaningTr: 'Yol ayrımı; planını büyütme zamanı.',
    ),
    TarotCard(
      id: 'wands_3',
      nameTr: 'Değnek Üçlüsü',
      nameEn: 'Three of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: '3',
      keywordsTr: ['genişleme', 'fırsat', 'beklenti'],
      shortMeaningTr: 'Ufuk açılır; emeklerin karşılığı yaklaşır.',
    ),
    TarotCard(
      id: 'wands_4',
      nameTr: 'Değnek Dörtlüsü',
      nameEn: 'Four of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: '4',
      keywordsTr: ['kutlama', 'ev', 'uyum'],
      shortMeaningTr: 'Sevinçli gelişme; düzen ve aidiyet artar.',
    ),
    TarotCard(
      id: 'wands_5',
      nameTr: 'Değnek Beşlisi',
      nameEn: 'Five of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: '5',
      keywordsTr: ['rekabet', 'gerilim', 'çatışma'],
      shortMeaningTr: 'Fikir çatışması; enerjiyi doğru yönet.',
    ),
    TarotCard(
      id: 'wands_6',
      nameTr: 'Değnek Altılısı',
      nameEn: 'Six of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: '6',
      keywordsTr: ['zafer', 'takdir', 'başarı'],
      shortMeaningTr: 'Görünür başarı; takdir ve özgüven.',
    ),
    TarotCard(
      id: 'wands_7',
      nameTr: 'Değnek Yedilisi',
      nameEn: 'Seven of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: '7',
      keywordsTr: ['savunma', 'direnç', 'kararlılık'],
      shortMeaningTr: 'Pozisyonunu koru; pes etme.',
    ),
    TarotCard(
      id: 'wands_8',
      nameTr: 'Değnek Sekizlisi',
      nameEn: 'Eight of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: '8',
      keywordsTr: ['hız', 'haber', 'akış'],
      shortMeaningTr: 'Hızlanan süreç; mesaj/haber gelebilir.',
    ),
    TarotCard(
      id: 'wands_9',
      nameTr: 'Değnek Dokuzlusu',
      nameEn: 'Nine of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: '9',
      keywordsTr: ['dayanıklılık', 'temkin', 'sınır'],
      shortMeaningTr: 'Yoruldun ama bitmedi; sınırlarını koru.',
    ),
    TarotCard(
      id: 'wands_10',
      nameTr: 'Değnek Onlusu',
      nameEn: 'Ten of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: '10',
      keywordsTr: ['yük', 'sorumluluk', 'baskı'],
      shortMeaningTr: 'Aşırı yük; paylaş, sadeleştir.',
    ),
    TarotCard(
      id: 'wands_page',
      nameTr: 'Değnek Uşağı',
      nameEn: 'Page of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: 'page',
      keywordsTr: ['merak', 'keşif', 'haber'],
      shortMeaningTr: 'Yeni heves; öğrenme ve deneme.',
    ),
    TarotCard(
      id: 'wands_knight',
      nameTr: 'Değnek Şövalyesi',
      nameEn: 'Knight of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: 'knight',
      keywordsTr: ['atak', 'macera', 'cesur adım'],
      shortMeaningTr: 'Hızlı hamle; acele riskini yönet.',
    ),
    TarotCard(
      id: 'wands_queen',
      nameTr: 'Değnek Kraliçesi',
      nameEn: 'Queen of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: 'queen',
      keywordsTr: ['çekim', 'özgüven', 'liderlik'],
      shortMeaningTr: 'Parlama dönemi; güçlü duruş.',
    ),
    TarotCard(
      id: 'wands_king',
      nameTr: 'Değnek Kralı',
      nameEn: 'King of Wands',
      arcana: 'minor',
      suit: 'wands',
      rank: 'king',
      keywordsTr: ['vizyon', 'otorite', 'girişim'],
      shortMeaningTr: 'Vizyoner liderlik; büyük resmi yönet.',
    ),

    // =========================
    // CUPS (Kupalar) 14
    // =========================
    TarotCard(
      id: 'cups_ace',
      nameTr: 'Kupa Ası',
      nameEn: 'Ace of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: 'ace',
      keywordsTr: ['sevgi', 'duygu', 'şifa'],
      shortMeaningTr: 'Kalp açılır; yeni duygu/şifa akışı.',
    ),
    TarotCard(
      id: 'cups_2',
      nameTr: 'Kupa İkilisi',
      nameEn: 'Two of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: '2',
      keywordsTr: ['bağ', 'uyum', 'ortaklık'],
      shortMeaningTr: 'Karşılıklı bağ; ilişki/ortaklık güçlenir.',
    ),
    TarotCard(
      id: 'cups_3',
      nameTr: 'Kupa Üçlüsü',
      nameEn: 'Three of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: '3',
      keywordsTr: ['kutlama', 'arkadaşlık', 'destek'],
      shortMeaningTr: 'Sosyal destek; sevinçli paylaşım.',
    ),
    TarotCard(
      id: 'cups_4',
      nameTr: 'Kupa Dörtlüsü',
      nameEn: 'Four of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: '4',
      keywordsTr: ['tatminsizlik', 'içe kapanma', 'fırsat'],
      shortMeaningTr: 'Duygusal durgunluk; fırsatı görmeye çalış.',
    ),
    TarotCard(
      id: 'cups_5',
      nameTr: 'Kupa Beşlisi',
      nameEn: 'Five of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: '5',
      keywordsTr: ['pişmanlık', 'kayıp', 'yas'],
      shortMeaningTr: 'Kayıp hissi; kalan iyiliğe odaklan.',
    ),
    TarotCard(
      id: 'cups_6',
      nameTr: 'Kupa Altılısı',
      nameEn: 'Six of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: '6',
      keywordsTr: ['anı', 'nostalji', 'masumiyet'],
      shortMeaningTr: 'Geçmiş teması; eski bağlar gündeme gelir.',
    ),
    TarotCard(
      id: 'cups_7',
      nameTr: 'Kupa Yedilisi',
      nameEn: 'Seven of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: '7',
      keywordsTr: ['seçenek', 'hayal', 'yanılsama'],
      shortMeaningTr: 'Çok seçenek; netleşmeden karar verme.',
    ),
    TarotCard(
      id: 'cups_8',
      nameTr: 'Kupa Sekizlisi',
      nameEn: 'Eight of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: '8',
      keywordsTr: ['bırakış', 'arayış', 'yolculuk'],
      shortMeaningTr: 'Tatmin etmeyeni bırak; anlam arayışı.',
    ),
    TarotCard(
      id: 'cups_9',
      nameTr: 'Kupa Dokuzlusu',
      nameEn: 'Nine of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: '9',
      keywordsTr: ['dilek', 'tatmin', 'keyif'],
      shortMeaningTr: 'Dilek kartı; memnuniyet artabilir.',
    ),
    TarotCard(
      id: 'cups_10',
      nameTr: 'Kupa Onlusu',
      nameEn: 'Ten of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: '10',
      keywordsTr: ['mutluluk', 'aile', 'tamamlanma'],
      shortMeaningTr: 'Duygusal tamamlanma; huzur ve birlik.',
    ),
    TarotCard(
      id: 'cups_page',
      nameTr: 'Kupa Uşağı',
      nameEn: 'Page of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: 'page',
      keywordsTr: ['mesaj', 'romantizm', 'yaratıcılık'],
      shortMeaningTr: 'Duygusal mesaj; tatlı bir gelişme.',
    ),
    TarotCard(
      id: 'cups_knight',
      nameTr: 'Kupa Şövalyesi',
      nameEn: 'Knight of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: 'knight',
      keywordsTr: ['teklif', 'romantik', 'yaklaşım'],
      shortMeaningTr: 'Kalpten teklif; duygusal adım.',
    ),
    TarotCard(
      id: 'cups_queen',
      nameTr: 'Kupa Kraliçesi',
      nameEn: 'Queen of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: 'queen',
      keywordsTr: ['empati', 'sezgi', 'şefkat'],
      shortMeaningTr: 'Duygusal olgunluk; empati ve sezgi güçlü.',
    ),
    TarotCard(
      id: 'cups_king',
      nameTr: 'Kupa Kralı',
      nameEn: 'King of Cups',
      arcana: 'minor',
      suit: 'cups',
      rank: 'king',
      keywordsTr: ['denge', 'olgunluk', 'sakin güç'],
      shortMeaningTr: 'Duyguyu yönetmek; sakin ve olgun yaklaşım.',
    ),

    // =========================
    // SWORDS (Kılıçlar) 14
    // =========================
    TarotCard(
      id: 'swords_ace',
      nameTr: 'Kılıç Ası',
      nameEn: 'Ace of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: 'ace',
      keywordsTr: ['hakikat', 'netlik', 'karar'],
      shortMeaningTr: 'Gerçek ortaya çıkar; keskin netlik.',
    ),
    TarotCard(
      id: 'swords_2',
      nameTr: 'Kılıç İkilisi',
      nameEn: 'Two of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: '2',
      keywordsTr: ['kararsızlık', 'engel', 'denge'],
      shortMeaningTr: 'Karar askıda; görmezden gelme.',
    ),
    TarotCard(
      id: 'swords_3',
      nameTr: 'Kılıç Üçlüsü',
      nameEn: 'Three of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: '3',
      keywordsTr: ['kalp kırığı', 'ayrılık', 'acı'],
      shortMeaningTr: 'Can yakıcı gerçek; iyileşme zaman ister.',
    ),
    TarotCard(
      id: 'swords_4',
      nameTr: 'Kılıç Dörtlüsü',
      nameEn: 'Four of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: '4',
      keywordsTr: ['dinlenme', 'toparlanma', 'sessizlik'],
      shortMeaningTr: 'Mola; zihni dinlendir, toparlan.',
    ),
    TarotCard(
      id: 'swords_5',
      nameTr: 'Kılıç Beşlisi',
      nameEn: 'Five of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: '5',
      keywordsTr: ['tartışma', 'ego', 'kayıp'],
      shortMeaningTr: 'Haklı çıkmak pahalı olabilir; seçimini yap.',
    ),
    TarotCard(
      id: 'swords_6',
      nameTr: 'Kılıç Altılısı',
      nameEn: 'Six of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: '6',
      keywordsTr: ['geçiş', 'iyileşme', 'yol'],
      shortMeaningTr: 'Zor dönemden çıkış; daha sakin sular.',
    ),
    TarotCard(
      id: 'swords_7',
      nameTr: 'Kılıç Yedilisi',
      nameEn: 'Seven of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: '7',
      keywordsTr: ['strateji', 'gizlilik', 'kurnazlık'],
      shortMeaningTr: 'Dikkat; gizli plan/kaçamak olabilir.',
    ),
    TarotCard(
      id: 'swords_8',
      nameTr: 'Kılıç Sekizlisi',
      nameEn: 'Eight of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: '8',
      keywordsTr: ['kısıt', 'korku', 'zihin tuzağı'],
      shortMeaningTr: 'Kendini sınırlama; çıkış yolu var.',
    ),
    TarotCard(
      id: 'swords_9',
      nameTr: 'Kılıç Dokuzlusu',
      nameEn: 'Nine of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: '9',
      keywordsTr: ['kaygı', 'uykusuzluk', 'endişe'],
      shortMeaningTr: 'Zihin yükü; gerçekçi adımlarla hafifler.',
    ),
    TarotCard(
      id: 'swords_10',
      nameTr: 'Kılıç Onlusu',
      nameEn: 'Ten of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: '10',
      keywordsTr: ['son', 'bitiriş', 'ders'],
      shortMeaningTr: 'Zor kapanış; ama yeni başlangıç kapıda.',
    ),
    TarotCard(
      id: 'swords_page',
      nameTr: 'Kılıç Uşağı',
      nameEn: 'Page of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: 'page',
      keywordsTr: ['merak', 'gözlem', 'soru'],
      shortMeaningTr: 'Bilgi toplama; keskin dikkat.',
    ),
    TarotCard(
      id: 'swords_knight',
      nameTr: 'Kılıç Şövalyesi',
      nameEn: 'Knight of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: 'knight',
      keywordsTr: ['hız', 'iddia', 'direktlik'],
      shortMeaningTr: 'Direkt hamle; kırıcı olmamaya dikkat.',
    ),
    TarotCard(
      id: 'swords_queen',
      nameTr: 'Kılıç Kraliçesi',
      nameEn: 'Queen of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: 'queen',
      keywordsTr: ['akıl', 'sınır', 'netlik'],
      shortMeaningTr: 'Duygudan çok akıl; net sınırlar.',
    ),
    TarotCard(
      id: 'swords_king',
      nameTr: 'Kılıç Kralı',
      nameEn: 'King of Swords',
      arcana: 'minor',
      suit: 'swords',
      rank: 'king',
      keywordsTr: ['adalet', 'mantık', 'otorite'],
      shortMeaningTr: 'Soğukkanlı karar; mantıkla yönet.',
    ),

    // =========================
    // PENTACLES (Tılsımlar) 14
    // =========================
    TarotCard(
      id: 'pentacles_ace',
      nameTr: 'Tılsım Ası',
      nameEn: 'Ace of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: 'ace',
      keywordsTr: ['fırsat', 'maddi', 'tohum'],
      shortMeaningTr: 'Somut fırsat; para/işte yeni başlangıç.',
    ),
    TarotCard(
      id: 'pentacles_2',
      nameTr: 'Tılsım İkilisi',
      nameEn: 'Two of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: '2',
      keywordsTr: ['denge', 'çoklu iş', 'uyum'],
      shortMeaningTr: 'İki işi birden yönetme; denge önemli.',
    ),
    TarotCard(
      id: 'pentacles_3',
      nameTr: 'Tılsım Üçlüsü',
      nameEn: 'Three of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: '3',
      keywordsTr: ['ekip', 'ustalık', 'işbirliği'],
      shortMeaningTr: 'Birlikte üretim; kalite yükselir.',
    ),
    TarotCard(
      id: 'pentacles_4',
      nameTr: 'Tılsım Dörtlüsü',
      nameEn: 'Four of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: '4',
      keywordsTr: ['tutunma', 'kontrol', 'biriktirme'],
      shortMeaningTr: 'Güvence ihtiyacı; fazla sıkma.',
    ),
    TarotCard(
      id: 'pentacles_5',
      nameTr: 'Tılsım Beşlisi',
      nameEn: 'Five of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: '5',
      keywordsTr: ['zorluk', 'kıtlık', 'destek'],
      shortMeaningTr: 'Maddi/duygusal zorlanma; destek aramak gerekli.',
    ),
    TarotCard(
      id: 'pentacles_6',
      nameTr: 'Tılsım Altılısı',
      nameEn: 'Six of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: '6',
      keywordsTr: ['paylaşım', 'yardım', 'denge'],
      shortMeaningTr: 'Al-ver dengesi; destek ve cömertlik.',
    ),
    TarotCard(
      id: 'pentacles_7',
      nameTr: 'Tılsım Yedilisi',
      nameEn: 'Seven of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: '7',
      keywordsTr: ['sabır', 'emek', 'bekleyiş'],
      shortMeaningTr: 'Emeğin meyve vermesi zaman ister.',
    ),
    TarotCard(
      id: 'pentacles_8',
      nameTr: 'Tılsım Sekizlisi',
      nameEn: 'Eight of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: '8',
      keywordsTr: ['çalışma', 'ustalaşma', 'disiplin'],
      shortMeaningTr: 'Düzenli emek; beceri artışı.',
    ),
    TarotCard(
      id: 'pentacles_9',
      nameTr: 'Tılsım Dokuzlusu',
      nameEn: 'Nine of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: '9',
      keywordsTr: ['bereket', 'konfor', 'öz değer'],
      shortMeaningTr: 'Kendi emeğinle konfor; öz değer yükselir.',
    ),
    TarotCard(
      id: 'pentacles_10',
      nameTr: 'Tılsım Onlusu',
      nameEn: 'Ten of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: '10',
      keywordsTr: ['miras', 'aile', 'güvence'],
      shortMeaningTr: 'Uzun vadeli güven; aile/işte sağlam zemin.',
    ),
    TarotCard(
      id: 'pentacles_page',
      nameTr: 'Tılsım Uşağı',
      nameEn: 'Page of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: 'page',
      keywordsTr: ['öğrenme', 'fırsat', 'başlangıç'],
      shortMeaningTr: 'Somut bir öğrenme/fırsat; yeni proje.',
    ),
    TarotCard(
      id: 'pentacles_knight',
      nameTr: 'Tılsım Şövalyesi',
      nameEn: 'Knight of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: 'knight',
      keywordsTr: ['istikrar', 'sabır', 'sorumluluk'],
      shortMeaningTr: 'Yavaş ama sağlam ilerleme.',
    ),
    TarotCard(
      id: 'pentacles_queen',
      nameTr: 'Tılsım Kraliçesi',
      nameEn: 'Queen of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: 'queen',
      keywordsTr: ['şefkat', 'bereket', 'pratiklik'],
      shortMeaningTr: 'Şefkatli düzen; pratik çözümler.',
    ),
    TarotCard(
      id: 'pentacles_king',
      nameTr: 'Tılsım Kralı',
      nameEn: 'King of Pentacles',
      arcana: 'minor',
      suit: 'pentacles',
      rank: 'king',
      keywordsTr: ['başarı', 'güvence', 'bolluk'],
      shortMeaningTr: 'Maddi istikrar; güvenli liderlik.',
    ),
  ];

  static List<TarotCard> shuffled() {
    final copy = List<TarotCard>.from(all);
    copy.shuffle();
    return copy;
  }
}
